title: Notes to myself (and anyone else) - Šimon Šmída
url: https://simonsmida.github.io

masthead_url: /notes/

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache
  - jekyll-feed

permalink: /notes/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      classes: wide

atom_feed:
  hide: true

footer:
  links:
    - label: "GitHub"
      url: "https://github.com/simonsmida"
    - label: "RSS"
      url: "/feed.xml"
