title: ... to myself (and anyone else) - Šimon Šmída
url: https://simonsmida.github.io

masthead_url: /notes/

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache
  - jekyll-feed

permalink: /notes/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      classes: wide

atom_feed:
  hide: true

footer:
  links:
    - label: "Personal Website"
      icon: "fas fa-globe"
      url: "https://simonsmida.github.io"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/simonsmida"
    - label: "Newsletter"
      icon: "fas fa-envelope"
      url: "https://buttondown.email/simonsmida"
    - label: "RSS"
      icon: "fas fa-rss"
      url: "/feed.xml"