remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"   # or "air", "contrast", "dark"

defaults:
  - scope:
      path: "notes"
    values:
      layout: single
      read_time: true
      toc: false
      toc_sticky: false

header:
  nav: false
  footer: false