remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: default

masthead:
  display: false

footer:
  links: []

defaults:
  - scope:
      path: "notes"
    values:
      layout: single
      classes: wide
      read_time: true
      author_profile: false
      share: false
      related: false
